### ISSUE TITLE
Could you please help me?

### ISSUE THREAD

**Issue by tomaskovacik** [tomaskovacik/BK3254#11]
Could you please help me?
I've got the module with the BK3254 and wired it up via UART. If I turn the module on it sends a few lines out (for example BT_CN), but I can't get it to respond to any comands listed in the datasheet.
I don't know what I do wrong but I just want to rename my device.

_Originally posted by @Largebytetechnology in https://github.com/tomaskovacik/BK8000L/issues/6#issuecomment-653906721_

**Comment by tomaskovacik** [comment]
most probably, you connect your TX pin to an incorrect pin  of the module

**Comment by Largebytetechnology** [comment]
I have already checked the wiring (even with continuity test). Would a module without UART put out these startup commands? Because I'm not sure if it supports UART. The local shop I bought it from claims that it supports it, but I'm not sure.

**Comment by tomaskovacik** [comment]
the serial interface is on pin 10 and 11 of the module, if you connect it there then it can be only one of:
- the module did not support serial interface (probably not, as you receiving data)
- damaged receive interface with 5V 
- bad transmission speed

**Comment by Largebytetechnology** [comment]
Is there anything to do other than setting the Baud Rate to 9600, select the COM port and sending the command: 
COM+SNAME+XXXXXXXXXXXXXXXX\r\n to change the name?

**Comment by tomaskovacik** [comment]
you have to have module with firmware >=1.2

**Comment by Largebytetechnology** [comment]
Is the version of the Firmware the version on the underside of the module?

**Comment by Largebytetechnology** [comment]
Now I found the problem. It was the dirty supply voltage for the RS232 to TTL converter. Now I can
communicate with the module but I still can't change the name.

**Comment by tomaskovacik** [comment]
> Is the version of the Firmware the version on the underside of the module?

correct

**Comment by Largebytetechnology** [comment]
My module has got v1.2 written on the bottom, so there is something wrong with the the command or some setting. I can give commands like Play/Pause (they work) but to COM+SNAME+BTBLUE\r\n it doesn't respond

**Comment by tomaskovacik** [comment]
what is module responce to COM+SNAME+TEST\r\n ?

**Comment by Largebytetechnology** [comment]
It doesn't respond at all.
However it does respond to some of the other commands listed in the datasheet.

**Comment by tomaskovacik** [comment]
maybe firmware version make sens only if module came from HYT, check if any of 1.2 commands works: https://github.com/tomaskovacik/BK3254/wiki/Supported-commands-and-event-send-from-module

**Comment by tomaskovacik** [comment]
try AT+MQ
https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fradiokot.ru%2Fforum%2Fviewtopic.php%3Ff%3D29%26t%3D157881

**Comment by Largebytetechnology** [comment]
It tells me: XZX-BK3254-V1. 1
Is there any way of updating the Firmware?

**Comment by tomaskovacik** [comment]
no there is not, this basicaly tell you that none of 1.2 firmware commands will works

**Comment by Largebytetechnology** [comment]
Ok thanks a lot for your help and time.
Do you know were I could get a v1.2 module with all the Features unlocked and reasonable shipping time?

**Comment by tomaskovacik** [comment]
I got my modules from aliexpress, from last batch of orders (1pcs to check what firmware module has, there are 2, buttons on ADC or one button on one pin of module) 

read readme for this repository, all is there, direct link tu product: https://www.aliexpress.com/item/32833631256.html
