### ISSUE TITLE
Which board do i choose for uploading?

### ISSUE THREAD

**Issue by Ollekkk** [tomaskovacik/BK3254#14]

**Comment by tomaskovacik** [comment]
uploading of what?

**Comment by Ollekkk** [comment]
To upload the Code from the Arduino IDE to the Board

**Comment by tomaskovacik** [comment]
code from arduino ide runs on arduino compatible board. No code is uploaded to bk3254 Bluetooth board.

**Comment by Ollekkk** [comment]
Ahhh thanks
