### ISSUE TITLE
Voice record

### ISSUE THREAD

**Issue by raetselandy** [tomaskovacik/BK3254#15]
Hey Tomas,

i have the F6888V1.1.
I want to Connect a microphone With the Module.
I also want to Connect a Button With the arduino mega 2560.

My goal is: if i press the Button, the microphone record my Voice and send it via Bluetooth to my pc.
I dont get how to Talk with the bluetoothmodul and wich Function i Need for this example.

Best regards
Andy

**Comment by tomaskovacik** [comment]
if you have bk2354 module connected over BT to the computer then microphone connected to the module can be used as input on the computer just select it in the audio menu of your OS. regarding button, if you like to have it as a trigger for starting recording on the computer then I do not know how to implement it ...

**Comment by raetselandy** [comment]
So i only select the microphone as Input on my pc and the Sound will Transfer?
So i dont need a arduino Code? Its automatic?

**Comment by tomaskovacik** [comment]
of course, take a few minutes and study datasheet:  https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/F-6888_bk3254/Bluetooth%20audio%20module%20BK3254%20manual%20V1.4_HYT_%20no%20pairing%20password.pdf

**Comment by raetselandy** [comment]
I already read it. its only Talk about the Command, but i dont understand wich of them are important for me.

If i Connect the Button Directory to the Module, will it be than possible to trigger the start of record?

**Comment by tomaskovacik** [comment]
you can try to use for example dial the last number, but you have to catch this avrcp command on the computer side (probably in BT stack) and call record command on the computer. This module was designed for use in BT speakers and so  no such function is directly implemented. And again I just write the library to simplify programing in arduino, I did not design this module ;)

**Comment by raetselandy** [comment]
Thank you very much!
This Project is really important for me.
If you have another idea Or Tipps how i can Transfer my Voice from the module to the pc, i will appreciate this Information.
If i ask a question again (maybe more specific), i Hope it would be okay for you. I dont want to disrupt you.
