### ISSUE TITLE
Work on STM32

### ISSUE THREAD

**Issue by Gegerd** [tomaskovacik/BK3254#6]
Hello, I ask for help. The description indicates what works with the STM32. Can you specify what needs to be changed to work with STM32?

**Comment by tomaskovacik** [comment]
nothing, just remember there is no software serial, so HW serial must be used

delete this line: SoftwareSerial swSerial(7, 6); //rxPin, txPin, inverse_logic
replace this line: BK3254 BT(&swSerial, resetBTpin);
with BK3254 BT(&Serial1, resetBTpin);

and in BK3254.h you need to comment out #define USE_SW_SERIAL
so it should looks like //#define USE_SW_SERIAL

so same as when using HW serial on any avr board in arduino environment.
