### ISSUE TITLE
HFP

### ISSUE THREAD

**Issue by xnatlive** [tomaskovacik/BK3254#8]
Hello
I'm building a sound system with this module controlled by atmega328p I wonder is it possible to disable phone call and use module as only music player

**Comment by tomaskovacik** [comment]
disconnnect HFP after connection?

**Comment by xnatlive** [comment]
No I meant dissabling HFP.  So the device only works as A2DP and does not transfer voice calls on sprakers.

**Comment by tomaskovacik** [comment]
I understand, only solution I can imagine is disable it in phone or via serial from atmega after connection is established.
